#!/bin/sh
# ORIGINALLY FROM LUKE SMITH
# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-firefox}

pgrep -x dmenu && exit

choice=$(echo "G" | dmenu -i -p "Search Google:") || exit 1

if [ "$choice" = "G"  ]; then
    $browser "https://google.com"
else
    if echo "$choice" | grep "^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$"; then
        $browser "$choice"
    else
        # choice = echo $choice | sed -e  's/ /+/g'
        $browser "https://google.com/search?q=$choice"
    fi
fi
