#!/bin/bash

colours_per_row=16

i=0
while [ $i -lt 256 ]; do
    j=0
    while [ $j -lt $colours_per_row ]; do
      colour=$((i + j))
      printf "\x1b[38;5;${colour}m %3d\x1b[0m " $colour
      j=$((j + 1))
    done
    echo # Newline after each row
    i=$((i + colours_per_row))
done
